version: '3'

services:
  frontend:
    image: nginx
    restart: always
    networks:
      - traefik
      - example
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatbot-frontend.rule=Host(`example.jurrevriesen.nl`)"
      - "traefik.http.routers.chatbot-frontend.entrypoints=websecure"
      - "traefik.http.routers.chatbot-frontend.priority=1"
      - "traefik.http.routers.chatbot-frontend.tls.certresolver=myresolver"
      - traefik.docker.network=traefik

networks:
  traefik:
    external: true
  example:      